### ISSUE TITLE
Timeline for 0.13 release?

### ISSUE THREAD

**Issue by thomaseizinger** [rust-analyzer/rowan#110]
Is there a timeline for an official 0.13 release?

I am trying to use rowan through [taplo](https://github.com/tamasfe/taplo) and I am not sure if taplo would be fine with depending on a RC.

**Comment by CAD97** [comment]
We're publishing non-rc versions again. Note that rowan still exists first to serve r-a, so breaking changes to serve r-a will still be coming as-needed, but we're tracking API breaks in the version number again.
