### ISSUE TITLE
NodeCache not exposed

### ISSUE THREAD

**Issue by withoutboats** [rust-analyzer/rowan#134]
`GreenNodeBuilder` has a public `with_cache` constructor, but the `NodeCache` type is not public and I can't see any way to construct one outside of the library.

**Comment by bjorn3** [comment]
Someone probably forgot to add it to https://github.com/rust-analyzer/rowan/blob/4d40c0084d1c0a6a17fe8912681c0113c82ef09a/src/lib.rs#L36 It is exported from the `green` module, so it seems to be intended to be public.
