### ISSUE TITLE
Bug with SyntaxPtr::to_node + many nodes with same range

### ISSUE THREAD

**Issue by azdavis** [rust-analyzer/rowan#144]
[`SyntaxNodePtr::to_node`][1] uses [`SyntaxNode::child_or_token_at_range`][2], whose docs state

> If there are several intersecting elements, any one can be returned.

This leads to issues (i.e. spurious panics) when there are indeed several elements that share the same range.

In my project, I have a [somewhat minimal reproducer][3]:

```
$ cargo t -p tests rowan_panic
    Finished test [unoptimized + debuginfo] target(s) in 0.13s
     Running unittests src/lib.rs (target/debug/deps/tests-bbc3b3005ec8d90f)

running 1 test
test misc::rowan_panic ... FAILED

failures:

---- misc::rowan_panic stdout ----
root: Root@0..17
  Whitespace@0..1 "\n"
  Dec@1..17
    DecWithTailInSeq@1..17
      DecWithTail@1..17
        DecInSeq@1..17
          FunctorDec@1..17
            FunctorKw@1..8 "functor"
            Whitespace@8..9 " "
            FunctorBind@9..17
              Name@9..16 "MkThing"
              Whitespace@16..17 "\n"
              Dec@17..17
                DecWithTail@17..17
    DecWithTail@17..17

=====
ptr: SyntaxNodePtr { kind: FunctorDec, range: 1..17 }
node: Root@0..17
node: Dec@1..17
node: DecWithTailInSeq@1..17
node: DecWithTail@1..17
node: DecInSeq@1..17
node: FunctorDec@1..17
resolved: FunctorDec@1..17
=====
ptr: SyntaxNodePtr { kind: Dec, range: 17..17 }
node: Root@0..17
node: Dec@1..17
node: DecWithTail@17..17
thread 'misc::rowan_panic' panicked at 'can't resolve local ptr to SyntaxNode: SyntaxNodePtr { kind: Dec, range: 17..17 }', crates/mlb-statics/src/lib.rs:358:24
```

The second ptr is to a Dec with range 17..17, which indeed exists, but it seems that this is not chosen for consideration and instead the DecWithTail with the same range is chosen instead. It does not have the same SyntaxKind, leading to the panic.

[1]: https://github.com/rust-analyzer/rowan/blob/295e5d03e822639b17144fcf51a4c3fb0ad774ed/src/ast.rs#L70-L88
[2]: https://github.com/rust-analyzer/rowan/blob/295e5d03e822639b17144fcf51a4c3fb0ad774ed/src/api.rs#L226-L233
[3]: https://github.com/azdavis/millet/tree/b48b35bd1b7931ed89614c8fbc0f3ea9d5b92df3

**Comment by Veykril** [comment]
I think the bigger problem here is you using empty tokens. Those are to my knowledge currently not supported with rowan and in turn can break a lot of other assumptions

**Comment by azdavis** [comment]
I don't think i'm using empty tokens, but i am using empty nodes. Dec and DecWithTail are two empty nodes (contain no tokens). Those are supported, right? Otherwise how would you represent parsing the empty string?

**Comment by Veykril** [comment]
Empty nodes aren't supported properly either I believe (not 100% sure on that), the empty string in my eyes would be two quotations marks, so it's not technically empty (assuming rust or similar languages)

**Comment by matklad** [comment]
Yeah, by design, rowan does not support empty nodes, because that would
made “get node/token by offset” operations ambiguous

**Comment by Veykril** [comment]
That's a special case that just works, an empty file is just a single empty node, so there is no problem with selection ambiguities

**Comment by azdavis** [comment]
Okay, I changed my code to not use empty nodes anymore:

- https://github.com/azdavis/language-util/commit/aa47bd96af2cc622635f97015864b943e90449d5
- https://github.com/azdavis/millet/commit/34bb2c869115cdb504f1be15ef94cd1d56d976bc

This then lets me go back to using upstream rowan instead of my fork which adds `try_to_node`:

- https://github.com/azdavis/language-util/commit/cc57f0aef443b16a8cd5a7506d11e182ab091e8d
- https://github.com/azdavis/millet/commit/f3169488ea7da0429069641ef0fd0ff983ce46c6

If we don't think adding `try_to_node` is useful in general I can close the relevant pr #148.

**Comment by azdavis** [comment]
Regardless of the pr we can close this issue as a wont-fix since empty nodes/tokens are not supported. Only possible follow up would be to document that somewhere if not already
