### ISSUE TITLE
Allow non UTF-8 source code

### ISSUE THREAD

**Issue by edgarogh** [rust-analyzer/rowan#157]
Currently, `rowan` [requires string slices](https://docs.rs/rowan/0.15.11/rowan/struct.GreenNodeBuilder.html#method.token). However, not all programming languages require UTF-8, which makes it impossible to represent them using a `rowan` tree without adding arbitrary rules to the existing specification. It would be convenient if we could, for instance, use byte slices as our base source code representation. If a maintainer has an idea of how this would work (how to specify whether or not Unicode is enforced using `&str`), I would love to draft a PR.

**Comment by matklad** [comment]
This is explicitly out of scope - rowan supports only utf8 documents. The best way to support other encodings would be to fork the library.

**Comment by edgarogh** [comment]
Ok, thanks for the information, I didn't know that.

**Comment by edgarogh** [comment]
For anyone reading this, it looks like Rune's [`syntree`](https://lib.rs/crates/syntree) library can be a good alternative. And it also provides a solution for #26.
