### ISSUE TITLE
Consider using (or offering using) nonstandard Arc without weak support

### ISSUE THREAD

**Issue by CAD97** [rust-analyzer/rowan#78]
e.g. [`triomphe`](https://lib.rs/crates/triomphe), [`elysees`](https://lib.rs/crates/elysees), or a custom one.

Our usage of `Arc` is currently entirely contained, so this could be done transparently. The alternate backend of sorbus exposes `Arc`, so would make this harder to do.

@RDambrosio016 reports a 55% (!) (valgrind-reported) drop in memory usage for switching to an `Arc` without weak reference support.

**Comment by CAD97** [comment]
I think this is done now that we're using a custom arc? @matklad

**Comment by matklad** [comment]
Ideed!
