### ISSUE TITLE
Hi what is the general purpose of this language?

### ISSUE THREAD

**Issue by Joe23232** [rust-analyzer/rowan#79]
I wanted to know is this an interpreted language or compiled language?

**Comment by bjorn3** [comment]
Rowan is not a language itself. It is a library that can be used to represent CST's for languages. CST stands for concrete syntax tree. Unlike AST (abstract syntax tree), a CST represents the parsed text in a lossless way. It includes every piece of whitespace and contains enough information to get the original input text even in case of syntax errors.
