### ISSUE TITLE
Can we do a quick release?

### ISSUE THREAD

**Issue by jD91mZM2** [rust-analyzer/rowan#98]
Hi!

I'd love to release `rnix-lsp` with a newer rowan+rnix, but first I need a release [containing this patch](https://github.com/rust-analyzer/rowan/pull/97) and then a release of nixpkgs-fmt with that new rowan version.

Thanks!

**Comment by lnicola** [comment]
I think `rowan` is published if you bump the version.

**Comment by lnicola** [comment]
@jD91mZM2 can you put up a PR that bumps the version in `Cargo.toml`?

**Comment by jD91mZM2** [comment]
Oh, that's cool. Absolutely, will do!
